name: CI - E2E + BDD + API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Prepare reports folder
        run: mkdir -p reports

      # ---------------------------
      # API (Cucumber @api)
      # ---------------------------
      - name: Run API tests (Cucumber @api)
        run: |
          npx cucumber-js \
            --require-module ts-node/register \
            --require "features/step_definitions/**/*.ts" \
            --tags @api \
            --format progress \
            --format html:reports/cucumber-api.html \
            features/**/*.feature

      # ---------------------------
      # BDD (sin @api)
      # ---------------------------
      - name: Run BDD tests (Cucumber)
        run: |
          npx cucumber-js \
            --require-module ts-node/register \
            --require "features/step_definitions/**/*.ts" \
            --format progress \
            --tags "not @api" \
            --format html:reports/cucumber-bdd.html \
            features/**/*.feature

      # ---------------------------
      # Artifacts
      # ---------------------------
      - name: Upload Cucumber reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cucumber-reports
          path: reports/
          retention-days: 30

      - name: Upload Evidence PDFs
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: evidencias-pdfs
          path: evidencias_pipeline/pdfs/*.pdf
          retention-days: 30
